config/routes.rb
Rails.application.routes.draw do
  resources :instances
  devise_for :users
  mount StripeEvent::Engine => '/events'
  root 'home#index'
end

app/models/instance.rb
class Instance < ActiveRecord::Base
  has_one :subscription
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  after_create :create_stripe_plan
  after_update :update_stripe_plan
  after_destroy { |plan| Stripe::Plan.retrieve(plan.id.to_s).delete }

  validates :amount, presence: true
  validates :currency, presence: true
  validates :interval, presence: true
  validates :name, presence: true

  has_many :subscriptions

  private
    def create_stripe_plan
      begin
        Stripe::Plan.create(
          id: self.id.to_s,
          amount: self.amount,
          currency: self.currency,
          interval: self.interval,
          interval_count: self.interval_count,
          name: self.name,
          trial_period_days: self.trial_period_days,
          metadata: self.metadata,
          statement_descriptor: self.statement_descriptor
        )
      rescue Stripe::StripeError => e
        logger.info e.message
      end
    end

    def update_stripe_plan
      begin
        p = Stripe::Plan.retrieve(self.id.to_s)
        p.name = self.name
        p.metadata = self.metadata
        p.statement_descriptor = self.statement_descriptor
        p.save
      rescue Stripe::StripeError => e
        logger.info e.message
        logger.info p
      end
    end
end

app/models/region.rb
class Region < ActiveRecord::Base
  
end

app/models/stripe_webhook.rb
class StripeWebhook < ActiveRecord::Base
  validates_uniqueness_of :stripe_id
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :plan, polymorphic: true
  belongs_to :instance, polymorphic: true

  include AASM

  aasm column: 'state', skip_validation_on_save: true do
    state :pending, initial: true
    state :processing
    state :active
    state :canceled
    state :errored

    event :process, after: :start_subscription do
      transitions from: :pending, to: :processing
    end

    event :activate do
      transitions from: :processing, to: :active
    end

    event :cancel do
      transitions from: :active, to: :canceled
    end

    event :fail do
      transitions from: [:pending, :processing], to: :errored
    end
  end

  private

  def start_subscription
    StartSubscription.call(self)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  after_create :create_stripe_customer

  has_many :instances

  private
    def create_stripe_customer
      begin
        customer = Stripe::Customer.create(email: self.email)
      rescue Stripe::StripeError => e
        logger.info e.message
      end
      self.stripe_customer_id = customer.id
      self.save
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_user!, only: :index
  respond_to :html

  def index
    @plans = Plan.all.order(:id)
    respond_with(@plans)
  end
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  before_filter :authenticate_user!

  before_action :set_instance, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def index
    @instances = current_user.instances.all
    respond_with(@instances)
  end

  def show
  end

  def new
    @instance = Instance.new
    @plans = Plan.all
    @plan = Plan.find_by_id(params[:plan]) || @plans.first
    @regions = Region.order(:slug)
    respond_with(@instance, @plans)
  end

  def create
    logger.info instance_params
    params.permit!.merge(
      stripe_token: instance_params[:stripeToken]
    )

    @instance = current_user.instances.new(instance_params)
    @instance.subscription = CreateSubscription.call(params)
    @instance.save
    respond_with(@instance)
  end

  private
    def set_instance
      @instance = current_user.instances.find(params[:id])
    end

    def instance_params
      params[:instance]
    end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: [:show, :edit, :update, :destroy]
  respond_to :html

  def index
    @plans = Plan.all
    respond_with(@plans)
  end

  def show
    respond_with(@plan)
  end

  def new
    @plan = Plan.new
    respond_with(@plan)
  end

  def edit
  end

  def create
    @plan = Plan.new(plan_params)
    @plan.save
    respond_with(@plan)
  end

  def update
    @plan.update(plan_params)
    respond_with(@plan)
  end

  def destroy
    @plan.destroy
    respond_with(@plan)
  end

  private
    def set_plan
      @plan = Plan.find(params[:id])
    end

    def plan_params
      params[:plan]
    end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_filter :find_plan_and_quantity, only: [:create]

  def create
    params.permit!.merge(
      plan: @plan,
      quantity: @quantity
    )

    CreateSubscription.call(params)
  end

  private
    def find_plan_and_quantity
      @plan = Plan.find_by!(id: params[:plan_id])
      @quantity = params[:quantity].blank? ? 1 : params[:quantity].to_i
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_class_for(flash_type)
    {
      :success => 'alert-success',
      :error => 'alert-danger',
      :alert => 'alert-warning',
      :notice => 'alert-info'
    }[flash_type.to_sym] || flash_type.to_s
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
 def devise_error_messages!
    return "" if resource.errors.empty?
    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
      <div class="alert alert-danger" role="alert">
        #{messages}
      </div>
      HTML
    html.html_safe
  end
end

app/views/home/index.html.slim
.jumbotron
  h1 PostGIS in a minute!
  p. Provision a PostGIS instance in the cloud and start developing your awesome geospatial applications.
  p
    = button_to "Sign up", new_registration_path(:user), method: :get, class: 'btn btn-lg btn-success'

.row
  - @plans.each do |plan|
    .col-lg-3.col-md-3.col-xs-6
      ul.plan class=(plan.featured ? 'featured': '')
        li.plan-name
          = plan.name
        - plan.metadata.each do |key, value|
          li class=(key=="Memory" ? 'plan-memory': '')
            strong = value
            |  #{key}
        li.plan-action
          = link_to "Sign up",
            new_instance_path(plan: plan.id),
            class: plan.featured ? "btn btn-lg btn-success" : "btn btn-default"

.row.marketing
  .h2 All Plans include
  .col-lg-6
    h4 Uptime
    p 99.99% Uptime SLA.
    h4 Disks
    p Solid-State Drives (SSD).
    h4 Multiple Datacenter Locations
    p Select the best US, Europe or Asia location based on latency.
  .col-lg-6
    h4 PostgreSQL
    p PostgreSQL 9.4.1 with all the extensions and data-types.
    h4 Latest PostGIS
    p PostGIS 2.1 with Topology, Raster and Tiger Geocoder extensions.
    h4 Admin Role
    p Admin role to create as many users and databases you like.

.row.marketing
  .h2 Pricing FAQ
  .col-lg-6
    h4 How am I billed?
    p Each database instance is billed hourly up to its monthly cost.
    h4 Am I charged when I enter a credit card?
    p No you are charged at the end of each month. We use your credit card to verify adequate funds.
    h4 How do I cancel my subscription?
    p You may cancel your subscription any time and we will only charge for the hours your database instance was alive.
  .col-lg-6
    h4 What form of payments do you accept?
    p We accept Visa, MasterCard, American Express, and Discover.
    h4 Do you offer refunds?
    p No, we do not offer refunds.
    h4 How much is additional bandwidth?
    p Additional bandwidth transfer is only 2¢ per GB.

app/views/instances/_form.html.slim
script src="//checkout.stripe.com/checkout.js"

= form_for @instance, url: {action: "create"}, html: {class: 'form-horizontal', role: 'form', id: 'new-instance-form' } do |f|
  .form-group
    = f.label :hostname, class: "col-sm-2 control-label"
    .col-sm-6
      = f.text_field :name, class: "form-control", autofocus: true
  .form-group
      = f.label :plan, class: "col-sm-2 control-label"
      .col-sm-6
        - for plan in @plans
          .radio
            label
              = radio_button_tag 'plan', plan.amount, checked = (plan.id == @plan.id)
              strong = plan.name
              = ": " + plan.metadata['Memory'] + " Memory, "
              = plan.metadata['Processor'] + " Processor, "
              = plan.metadata['Storage'] + " Storage and "
              = plan.metadata['Bandwidth'] + " Bandwidth"
  .form-group
      = f.label :region, class: "col-sm-2 control-label"
      .col-sm-6
        - for region in @regions
          .radio
            label
              = radio_button_tag 'region', region.slug
              strong = region.name
  .form-group
    .col-sm-offset-2.col-sm-10
      button#checkout.btn.btn-primary type="submit"  New Instance

javascript:
  $('#new-instance-form').bootstrapValidator({
    fields: {
      'instance[name]': {
        validators: {
          notEmpty: {
            message: 'The hostname is required.'
          }
        }
      },
      plan: {
        validators: {
          notEmpty: {
            message: 'Please select a plan.'
          }
        }
      },
      region: {
        validators: {
          notEmpty: {
            message: 'Please select a region.'
          }
        }
      }
    }
  }).on('success.form.bv', function(e) {
    e.preventDefault();
    var form = $(e.target);
    var bv = form.data('bootstrapValidator');

    var handler = StripeCheckout.configure({
      key: '#{{Rails.application.secrets.stripe_publishable_key}}',
      token: function(token) {
        // Use the token to create the charge with a server-side script.
        // You can access the token ID with `token.id`
        form.append($('<input type="hidden" name="stripeToken" />').val(token.id));
        bv.defaultSubmit();
      }
    });

    handler.open({
      name: 'SpacialDB UG',
      currency: 'EUR',
      description: 'Monthly Subscription',
      email: '#{{current_user.email}}',
      panelLabel: "Subscribe",
      amount: $('input:radio[name=plan]:checked').val()
    });

    // Close Checkout on page navigation
    $(window).on('popstate', function() {
      handler.close();
    });
  });

app/views/instances/index.html.slim
.row
  .col-md-2.sidebar
    = link_to 'New Instance', new_instance_path, class: 'btn btn-lg btn-success'

  .col-md-10
    h1 Instances

    table
      thead
        tr
          th ID
          th
          th
          th

      tbody
        - @instances.each do |instance|
          tr
            td = instance.id
            td = link_to 'Show', instance
            td = link_to 'Edit', edit_instance_path(instance)
            td = link_to 'Destroy', instance, data: {:confirm => 'Are you sure?'}, :method => :delete

app/views/instances/new.html.slim
.row
  .col-md-2.sidebar
    = button_to 'New Instance', new_instance_path, class: 'btn btn-lg btn-success'

  .col-md-10
    h2
      | New Instance

    == render 'form'

app/views/instances/show.html.slim
pre
  =@instance.attributes.to_json

=link_to "Back to instances", instances_path

app/views/layouts/_footer.html.slim
footer.footer
  p © SpacialDB UG 2014

app/views/layouts/_ga.html.slim
javascript:
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-56777164-1', 'auto');
  ga('send', 'pageview');

app/views/layouts/_header.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top role="navigation"
  .container
    .navbar-header
      button.navbar-toggle.collapsed aria-controls="navbar" aria-expanded="false" data-target="#navbar" data-toggle="collapse" type="button"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      a.navbar-brand href=root_path  SpacialDB
    #navbar.collapse.navbar-collapse
      ul.nav.navbar-nav
        li.active
          a href="#"  Home
        li
          a href="#about"  About
        li
          a href="#contact"  Contact
      ul.nav.navbar-nav.navbar-right
        li
          - if user_signed_in?
            = button_to "Sign out", destroy_user_session_path, method: :delete, class: 'btn btn-default navbar-btn'
          - else
            = button_to "Sign in", new_session_path(:user), method: :get, class: 'btn btn-default navbar-btn'

app/views/layouts/_messages.html.slim
- flash.each do |type, msg|
  - if msg.is_a?(String)
    div class="alert #{alert_class_for(type)} alert-dismissible" role="alert"
      button.close[type="button" data-dismiss="alert" aria-hidden="true"]
        span aria-hidden="true"  &times;
        span.sr-only Close
      =msg

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SpacialDB</title>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>

  <%= render 'layouts/ga' %>
</body>
</html>